secrets:
  ddns_api_key:
    file: ../../_secrets/ddns_api_key.txt

services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: always
    environment:
      API_KEY_FILE: /run/secrets/ddns_api_key
      ZONE: ${DOMAIN_NAME}
      PROXIED: false
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    secrets:
      - ddns_api_key
