networks:
  web:
    external: true

services:
  actual-helpers:
    container_name: actual-helpers
    image: ghcr.io/psybers/actual-helpers:latest
    env_file: .env
    volumes:
      - ${SSD_PATH}/actual-helpers/cache:/usr/src/app/cache
    environment:
      - PUID=1000
      - PGID=1000
