version: "3.7"

networks:
  web:
    external: true

services:
  pihole:
      container_name: pihole
      networks:
        - web
      restart: unless-stopped
      domainname: jeffslord.com
      #hostname: pihole
      image: pihole/pihole:latest
      dns:
        - 127.0.0.1
        - 1.1.1.1
      cap_add:
        - NET_ADMIN
      ports:
        #- '0.0.0.0:53:53/tcp'
        - '0.0.0.0:53:53/udp'
        - '0.0.0.0:67:67/udp'
        - '0.0.0.0:8053:80/tcp'
      volumes:
        - ${SSD}/pihole/:/etc/pihole/
        - ${SSD}/pihole/dnsmasqd:/etc/dnsmasq.d/
        #- ./pihole.log:/var/log/pihole.log
        - ${SSD}/pihole/pihole.log:/var/log/pihole.log
      environment:
        ServerIP: 192.168.1.200
        PROXY_LOCATION: pihole
        VIRTUAL_HOST: pihole.jeffslord.com
        VIRTUAL_PORT: 80
        TZ: 'America/Chicago'
        WEBPASSWORD: myserver
        DNS1: 127.0.0.1
        DNS2: 1.1.1.1
