version: '3'

networks:
  web:
    external: true

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    container_name: mc-server
    restart: unless-stopped
    networks:
      - web
    ports:
      - "25565:25565"
    volumes:
      - ${SSD_BASE_PATH}/games/minecraft/cobblemon_bcg:/data
      - ${SSD_BASE_PATH}/games/minecraft/modpacks:/modpacks
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      TZ: America/New_York
      VERSION: "1.20.1"

      # Overrides
      REPLACE_ENV_VARIABLES: "true"
      OVERRIDE_SERVER_PROPERTIES: "true"

      # Curse Forge
      # CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/${MOD_NAME}
      # CF_FILENAME_MATCHER: 0.4.0
      # CF_API_KEY: ${CF_API_KEY}
      MOD_PLATFORM: "CURSEFORGE"
      CF_SERVER_MOD: "/modpacks/BCG-2.9.3.zip"
      # VERSION: 1.20.1

      # Resources
      MEMORY: "16G"
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"

      # RCON
      ENABLE_RCON: true
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016

      # Server Properties
      ENABLE_ROLLING_LOGS: true
      SERVER_NAME: Jeff time
      OPS: |
        jeoffrey
      DIFFICULTY: "normal"
      MODE: survival
      PVP: false
      LEVEL: world_5
      # LEVEL_TYPE: minecraft:amplified
      MAX_PLAYERS: 10
      VIEW_DISTANCE: 20
      SIMULATION_DISTANCE: 10
      ALLOW_FLIGHT: TRUE
      MOTD: "**Cobblemon BCG 2.9.3**"
      SPAWN_PROTECTION: 16
      MAX_TICK_TIME: -1

      # Autopause
      ENABLE_AUTOPAUSE: TRUE
      AUTOPAUSE_TIMEOUT_EST: 360
      AUTOPAUSE_TIMEOUT_INIT: 360

  minecraft-backup:
    image: itzg/mc-backup
    container_name: mc-backup
    restart: unless-stopped
    networks:
      - web
    environment:
      TZ: America/New_York
      RCON_HOST: mc-server
      RCON_PORT: 28016
      RCON_PASSWORD: "testing"
      BACKUP_INTERVAL: "6h"
      PRUNE_BACKUPS_DAYS: 4
      # instead of network_mode below, could declare RCON_HOST
      # RCON_HOST: mc
    volumes:
      # mount the same volume used by server, but read-only
      - ${SSD_BASE_PATH}/games/minecraft/cobblemon_bcg:/data:ro
      # use a host attached directory so that it in turn can be backed up
      # to external/cloud storage
      - ${HDD_BASE_PATH}/games/minecraft/cobblemon_bcg/backups:/backups
      # share network namespace with server to simplify rcon access
      # network_mode: "service:mc-server"
