version: "3.7"

networks:
  web:
    external: true

services:
  # Media Player
  plex:
    image: "plexinc/pms-docker:latest"
    # image: linuxserver/plex
    container_name: plex
    networks:
      - web
    restart: unless-stopped
    # network_mode: host
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - ADVERTISE_IP=http://192.168.1.200:32400/
      - TZ=America/New_York
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=1000
      - PLEX_GID=1000
    volumes:
      - ${HDD}/config/plex:/config
      - ${HDD}/transcode:/transcode
      - ${HDD}/libraries/shows:/data/tvshows
      - ${HDD}/libraries/movies:/data/movies
      - ${HDD}/libraries/anime:/data/anime
      - ${HDD}/libraries/anime_movies:/data/anime_movies
  # Media Organizers
  sonarr:
    image: "linuxserver/sonarr:latest"
    container_name: sonarr
    networks:
      - web
    expose:
      - "8989"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HDD}/config/sonarr:/config
      - ${HDD}:/media
    depends_on:
      - prowlarr
      - deluge
    restart: unless-stopped
  radarr:
    image: "linuxserver/radarr:latest"
    container_name: radarr
    networks:
      - web
    expose:
      - "7878"
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - ${HDD}/config/radarr:/config
      - ${HDD}:/media
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - prowlarr
      - deluge
    restart: unless-stopped
  # jackett:
  #   image: "linuxserver/jackett:latest"
  #   container_name: jackett
  #   networks:
  #     - web
  #   expose:
  #     - "9117"
  #   environment:
  #     - PGID=1000
  #     - PUID=1000
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - ${HDD}/config/jackett:/config
  #     - ${HDD}/downloads:/downloads
  #   sysctls:
  #     - net.ipv6.conf.all.disable_ipv6=1
  #   restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - web
    expose:
      - "8191"
    environment:
      - LOG_LEVEL=debug
      - LOG_HTML=true
      - TZ=America/New_York
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    networks:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${SSD}/config:/config
    expose:
      - "9696"
    restart: unless-stopped
  # Downloader
  deluge:
    image: "binhex/arch-delugevpn:latest"
    container_name: deluge
    networks:
      - web
    env_file:
      - ../global.env
    cap_add:
      - NET_ADMIN
    #    sysctls:
    #      - net.ipv4.conf.all.src_valid_mark=1
    #    privileged: true
    expose:
      - "8112"
      - "8118"
      - "58846"
      - "58946"
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=${VPN_USER}
      - VPN_PASS=${VPN_PASS}
      - VPN_PROV=pia
      #      - VPN_CLIENT=wireguard
      - VPN_CLIENT=openvpn
      - STRICT_PORT_FORWARD=no #want this to be yes, but pia is changing to new type of server, causing issue
      #      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=192.168.112.1/24
      - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1
      - DELUGE_DAEMON_LOG_LEVEL=info
      - ADDITIONAL_PORTS=1234
      - DEBUG=false
      - UMASK=000
      - PUID=1000
      - PGID=1000
    volumes:
      - ${HDD}/downloads:/downloads
      - ${HDD}/config/deluge:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  # Analytics
  tautulli:
    image: "linuxserver/tautulli:latest"
    container_name: tautulli
    networks:
      # - traefik
      - web
    expose:
      - "8181"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - ${HDD}/config/plexpy:/config
      - ${HDD}/config/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    depends_on:
      - plex
    restart: unless-stopped
  # Request new media
  ombi:
    image: "linuxserver/ombi:latest"
    container_name: ombi
    networks:
      - web
    expose:
      - "3579"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - ${HDD}/config/ombi:/config
    depends_on:
      - plex
    restart: unless-stopped
  # Media Portal
  muximux:
    image: "linuxserver/muximux:latest"
    container_name: muximux
    networks:
      - web
    expose:
      - "8079"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - ${HDD}/config/muximux:/config
    depends_on:
      - plex
    restart: unless-stopped
  # Subtitles
  bazarr:
    image: "linuxserver/bazarr:latest"
    container_name: bazarr
    networks:
      - web
    expose:
      - "6767"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - ${HDD}/config/bazarr:/config
      - ${HDD}/libraries/shows:/data/tvshows
      - ${HDD}/libraries/movies:/data/movies
      - ${HDD}/libraries/anime:/data/anime
      - ${HDD}/libraries/anime_movies:/data/anime_movies
    depends_on:
      - plex
    restart: unless-stopped
  # ebooks / comics
  ubooquity:
    image: linuxserver/ubooquity
    container_name: ubooquity
    networks:
      - web
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - ${HDD}/config/ubooquity:/config
      - ${HDD}/libraries/books:/books
      - ${HDD}/libraries/comics:/comics
      - ${HDD}/libraries/raw_files:/filesi
    expose:
      - "2202"
      - "2203"
    restart: unless-stopped
  # audiobooks
  booksonic:
    image: linuxserver/booksonic
    container_name: booksonic
    networks:
      - web
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - ${HDD}/config/booksonic:/config
      - ${HDD}/libraries/audiobooks:/audiobooks
      - ${HDD}/libraries/podcasts:/podcasts
      - ${HDD}/libraries/other_audio:/othermedia
    expose:
      - "4040"
    restart: unless-stopped
