version: "3.7"
services:
  # Media Player
  plex:
    image: "plexinc/pms-docker:latest"
    # image: linuxserver/plex
    container_name: plex
    networks:
      - traefik
    restart: unless-stopped
    # network_mode: host
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    # expose:
    #   - "32400"
    #   - "3005"
    #   - "8324"
    #   - "32469"
    #   - "1900"
    #   - "32410"
    #   - "32412"
    #   - "32413"
    #   - "32414"
    environment:
      - ADVERTISE_IP=http://192.168.1.200:32400/
      - TZ=America/New_York
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=1000
      - PLEX_GID=1000
      # - PUID=1000
      # - PGID=1000
      # - VERSION=docker
      # - UMASK_SET=022 #optional
      # - PLEX_CLAIM="claim-qxVKRrNKy9x1WQXzEJxD"
    volumes:
      - ${HDD_BASE_PATH}/config/plex:/config
      - ${HDD_BASE_PATH}/transcode:/transcode
      - ${HDD_BASE_PATH}/libraries/shows:/data/tvshows
      - ${HDD_BASE_PATH}/libraries/movies:/data/movies
      - ${HDD_BASE_PATH}/libraries/anime:/data/anime
      - ${HDD_BASE_PATH}/libraries/anime_movies:/data/anime_movies
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.${DOMAIN_NAME}`)
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.routers.plex.tls.certresolver=myresolver
  # Media Organizers
  sonarr:
    image: "linuxserver/sonarr:latest"
    container_name: sonarr
    networks:
      - traefik
    # ports:
    #   - "8989:8989"
    expose:
      - "8989"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HDD_BASE_PATH}/config/sonarr:/config
      - ${HDD_BASE_PATH}/libraries/shows:/data/tvshows
      - ${HDD_BASE_PATH}/libraries/anime:/data/anime
      - ${HDD_BASE_PATH}/downloads:/downloads
    depends_on:
      - jackett
      - deluge
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN_NAME}`)
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.routers.sonarr.tls.certresolver=myresolver
      
  radarr:
    image: "linuxserver/radarr:latest"
    container_name: radarr
    networks:
      - traefik
    # ports:
    #   - "7878:7878"
    expose:
      - "7878"
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - ${HDD_BASE_PATH}/config/radarr:/config
      - ${HDD_BASE_PATH}/downloads:/downloads
      - ${HDD_BASE_PATH}/libraries/movies:/data/movies
      - ${HDD_BASE_PATH}/libraries/anime_movies:/data/anime_movies
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - jackett
      - deluge
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN_NAME}`)
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=myresolver
  # Indexer
  jackett:
    image: "linuxserver/jackett:latest"
    container_name: jackett
    networks:
      - traefik
    # ports:
    #   - "9117:9117"
    expose:
      - "9117"
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HDD_BASE_PATH}/config/jackett:/config
      - ${HDD_BASE_PATH}/downloads:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN_NAME}`)
      - traefik.http.routers.jackett.tls=true
      - traefik.http.routers.jackett.tls.certresolver=myresolver
  # Downloader
  deluge:
    image: "binhex/arch-delugevpn:latest"
    container_name: deluge
    networks:
      - traefik
    cap_add:
      - NET_ADMIN
    expose:
      - "8112"
      - "8118"
      - "58846"
      - "58946"
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=${VPN_USER}
      - VPN_PASS=${VPN_PASS}
      - VPN_PROV=pia
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=209.222.18.222,37.235.1.174,1.1.1.1,8.8.8.8,209.222.18.218
      - DEBUG=false
      - UMASK=000
      - PUID=1000
      - PGID=1000
    volumes:
      - ${HDD_BASE_PATH}/downloads:/downloads
      - ${HDD_BASE_PATH}/config/deluge:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.deluge.rule=Host(`deluge.${DOMAIN_NAME}`)
      - traefik.http.routers.deluge.tls=true
      - traefik.http.routers.deluge.tls.certresolver=myresolver
  # Analytics
  tautulli:
    image: "linuxserver/tautulli:latest"
    container_name: tautulli
    networks:
      - traefik
    # ports:
    #   - "8181:8181"
    expose:
      - "8181"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - ${HDD_BASE_PATH}/config/plexpy:/config
      - ${HDD_BASE_PATH}/config/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    depends_on:
      - plex
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli.rule=Host(`tautulli.${DOMAIN_NAME}`)
      - traefik.http.routers.tautulli.tls=true
      - traefik.http.routers.tautulli.tls.certresolver=myresolver
  # Request new media
  ombi:
    image: "linuxserver/ombi:latest"
    container_name: ombi
    networks:
      - traefik
    # ports:
        # - "3579:3579"
    expose:
      - "3579"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - ${HDD_BASE_PATH}/config/ombi:/config
    depends_on:
      - plex
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.ombi.rule=Host(`ombi.${DOMAIN_NAME}`)
      - traefik.http.routers.ombi.tls=true
      - traefik.http.routers.ombi.tls.certresolver=myresolver
  # Media Portal
  muximux:
    image: "linuxserver/muximux:latest"
    container_name: muximux
    networks:
      - traefik
    expose:
      - "8079"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - ${HDD_BASE_PATH}/config/muximux:/config
    depends_on:
      - plex
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.muximux.rule=Host(`muximux.${DOMAIN_NAME}`)
      - traefik.http.routers.muximux.tls=true
      - traefik.http.routers.muximux.tls.certresolver=myresolver
  # Subtitles
  bazarr:
    image: "linuxserver/bazarr:latest"
    container_name: bazarr
    networks:
      - traefik
    # ports:
    #     - "6767:6767"
    expose:
      - "6767"
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    volumes:
      - ${HDD_BASE_PATH}/config/bazarr:/config
      - ${HDD_BASE_PATH}/libraries/shows:/data/tvshows
      - ${HDD_BASE_PATH}/libraries/movies:/data/movies
      - ${HDD_BASE_PATH}/libraries/anime:/data/anime
      - ${HDD_BASE_PATH}/libraries/anime_movies:/data/anime_movies
    depends_on:
      - plex
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN_NAME}`)
      - traefik.http.routers.bazarr.tls=true
      - traefik.http.routers.bazarr.tls.certresolver=myresolver
  # ebooks / comics
  ubooquity:
    image: linuxserver/ubooquity
    container_name: ubooquity
    networks:
     - traefik
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - ${HDD_BASE_PATH}/config/ubooquity:/config
      - ${HDD_BASE_PATH}/libraries/books:/books
      - ${HDD_BASE_PATH}/libraries/comics:/comics
      - ${HDD_BASE_PATH}/libraries/raw_files:/filesi
    expose:
      - "2202"
      - "2203"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.ubooquity.rule=Host(`ubooquity.${DOMAIN_NAME}`)
      - traefik.http.routers.ubooquity.tls=true
      - traefik.http.routers.ubooquity.tls.certresolver=myresolver
  # audiobooks
  booksonic:
    image: linuxserver/booksonic
    container_name: booksonic
    networks:
      - traefik
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - ${HDD_BASE_PATH}/config/booksonic:/config
      - ${HDD_BASE_PATH}/libraries/audiobooks:/audiobooks
      - ${HDD_BASE_PATH}/libraries/podcasts:/podcasts
      - ${HDD_BASE_PATH}/libraries/other_audio:/othermedia
    expose:
      - "4040"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.booksonic.rule=Host(`booksonic.${DOMAIN_NAME}`)
      - traefik.http.routers.booksonic.tls=true
      - traefik.http.routers.booksonic.tls.certresolver=myresolver
  # groceries
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    networks:
      - traefik
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - ${SSD_BASE_PATH}/grocy/config:/config
    expose:
      - "9283"
    labels:
      - traefik.enable=true
      - traefik.http.routers.grocy.rule=Host(`grocy.${DOMAIN_NAME}`)
      - traefik.http.routers.grocy.tls=true
      - traefik.http.routers.grocy.tls.certresolver=myresolver
    restart: unless-stopped

  piwigo:
    image: linuxserver/piwigo
    container_name: piwigo
    networks:
      - traefik
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - ${HDD_BASE_PATH}/config/piwigo/config:/config
    expose:
      - "4049"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.piwigo.rule=Host(`piwigo.${DOMAIN_NAME}`)
      - traefik.http.routers.piwigo.tls=true
      - traefik.http.routers.piwigo.tls.certresolver=myresolver

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    networks:
      - traefik
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=ADMIN_PASS
      - TZ=America/New_York
      - MYSQL_DATABASE=HOME #optional
      - MYSQL_USER=JEFF #optional
      - MYSQL_PASSWORD=JEFF_PASS #optional
      # - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - ${HDD_BASE_PATH}/db/mariadb/config:/config
    expose:
      - "3306"
    labels:
      - traefik.enable=true
      - traefik.http.routers.mariadb.rule=Host(`mariadb.${DOMAIN_NAME}`)
      - traefik.http.routers.mariadb.tls=true
      - traefik.http.routers.mariadb.tls.certresolver=myresolver



networks:
  traefik:
    external: true
